// Chinese is the source copy used throughout the renderer. Only exact UI copy is
// translated, so filenames, user input, paths and backend logs are never changed.
const EN = {
  // Shell, navigation and common actions.
  "纹理处理": "Texture Tools",
  "风格实验室": "Style Lab",
  "字符与线条": "Characters & Lines",
  "故障与信号": "Glitch & Signal",
  "绘画与手作": "Painting & Craft",
  "像素与印刷": "Pixels & Print",
  "色彩与纹理": "Color & Texture",
  "光学与扭曲": "Optics & Distortion",
  "AI 图像": "AI Images",
  "材质生成": "Material Generation",
  "资源与系统": "Resources & System",
  "PBR 合成": "PBR Merge",
  "PBR 拆分": "PBR Split",
  "BLK 生成": "BLK Generator",
  "涂装打包": "Skin Packaging",
  "Mipmap": "Mipmap",
  "图片转 DDS": "Image to DDS",
  "图片转 ASCII": "Image to ASCII",
  "AI 抠图": "AI Cutout",
  "动漫超分": "Anime Upscale",
  "通用超分": "General Upscale",
  "生成法线图": "Generate Normal Map",
  "生成高度图": "Generate Height Map",
  "模型烘焙": "Model Baking",
  "涂装管理": "Skin Manager",
  "应用设置": "Application Settings",
  "设置": "Settings",
  "任务参数": "Task Settings",
  "待配置": "Needs Setup",
  "配置完成后可开始运行": "Ready to run",
  "当前模式无需运行": "No processing needed in this mode",
  "运行记录": "Activity",
  "暂无任务": "No tasks yet",
  "选择": "Choose",
  "选择目录": "Choose Folder",
  "选择图片": "Choose Image",
  "打开": "Open",
  "添加": "Add",
  "关闭": "Close",
  "清空": "Clear",
  "刷新预览": "Refresh Preview",
  "适应窗口": "Fit to Window",
  "恢复默认": "Restore Defaults",
  "浏览": "Browse",
  "输入": "Input",
  "输出": "Output",
  "格式": "Format",
  "预设": "Presets",
  "结果": "Results",
  "原图": "Original",
  "模型": "Model",
  "材质": "Material",
  "显示": "Display",
  "保存当前": "Save Current",
  "开始烘焙": "Start Baking",
  "取消烘焙": "Cancel Baking",
  "开始合成": "Start Merge",
  "开始拆分": "Start Split",
  "开始转换": "Start Conversion",
  "开始抠图": "Start Cutout",
  "停止": "Stop",
  "处理中…": "Processing…",
  "准备": "Preparing",
  "正在准备任务": "Preparing task",
  "网页演示 · 请在桌面软件中导入并生成": "Browser preview · Import and generate in the desktop app",
  "请使用桌面版": "Use the desktop app",
  "选择目录后即可管理涂装": "Choose a folder to manage skins",
  "尚未连接 UserSkins 目录": "UserSkins folder not connected",
  "0 个涂装": "0 skins",
  "0 张素材": "0 source images",
  "0 项": "0 items",

  // Settings.
  "更新、数据路径与版本信息": "Updates, data paths and version information",
  "更新、数据与版本信息": "Updates, data and version information",
  "界面语言": "Interface Language",
  "选择应用界面的显示语言": "Choose the language used by the interface",
  "切换后立即生效，并在下次启动时保留。": "Changes apply immediately and are saved for next launch.",
  "侧栏导航": "Sidebar Navigation",
  "风格实验室分类的展开方式": "How Style Lab categories expand",
  "切换区域时自动收起其他分类": "Collapse other categories when switching sections",
  "默认开启。展开另一分类或切换到其他功能时，自动收起之前的分类；关闭后可同时展开多组。": "On by default. Opening another category or feature closes the previous one. Turn it off to keep several categories open.",
  "更新": "Updates",
  "保持应用版本最新": "Keep the app up to date",
  "启动时自动检查更新": "Check for updates at startup",
  "检查更新": "Check for Updates",
  "正在读取版本…": "Reading version…",
  "默认目录与文件冲突策略": "Default folder and filename conflicts",
  "默认输出目录": "Default Output Folder",
  "目录策略": "Folder Policy",
  "输出目录策略": "Output Folder Policy",
  "沿用各模块记录的目录（默认）": "Use each feature's saved folder (default)",
  "始终使用默认输出目录": "Always use the default output folder",
  "跟随输入文件所在目录": "Use the input file's folder",
  "文件冲突策略": "Filename Conflict Policy",
  "直接覆盖同名文件（默认）": "Overwrite files with the same name (default)",
  "自动追加 -1/-2 后缀，不覆盖": "Append -1/-2 instead of overwriting",
  "目录策略对抠图、超分、PBR、Mipmap、转 DDS 与材质生成生效；冲突策略对这些任务及模型烘焙导出生效。BLK 覆盖仍需单独确认。": "Folder policy applies to cutout, upscale, PBR, Mipmap, DDS conversion and material maps. Conflict policy also applies to model bake exports. BLK overwrites still require confirmation.",
  "通知": "Notifications",
  "长任务完成提醒": "Long-running task alerts",
  "任务完成时发送系统通知": "Send a system notification when a task finishes",
  "抠图、超分、烘焙等长任务完成或失败时弹系统通知，适合最小化窗口挂后台等结果。": "Show a system notification when cutout, upscale or baking finishes or fails, even when the window is minimized.",
  "存储": "Storage",
  "缓存清理与模型管理": "Cache cleanup and model management",
  "缩略图缓存：读取中…": "Thumbnail cache: loading…",
  "烘焙缓存：读取中…": "Bake cache: loading…",
  "缩略图缓存：桌面版可查看": "Thumbnail cache: available in desktop app",
  "烘焙缓存：桌面版可查看": "Bake cache: available in desktop app",
  "已安装模型与运行库": "Installed models and runtimes",
  "清理": "Clean",
  "清理过期项": "Clean Expired",
  "仅清理超过 24 小时且未被结果引用的缓存": "Only remove cache older than 24 hours that no result references",
  "应用数据": "App Data",
  "配置与路径记录": "Settings and saved paths",
  "配置目录": "Settings Folder",
  "重置所有设置": "Reset All Settings",
  "关于": "About",
  "版本": "Version",
  "框架": "Framework",
  "平台": "Platform",
  "作者": "Author",
  "联系方式": "Contact",
  "仓库": "Repository",
  "镜像": "Mirror",
  "许可证": "License",
  "切换到深色主题": "Switch to dark theme",
  "切换到浅色主题": "Switch to light theme",
  "切换黑白主题": "Toggle theme",
  "收起侧栏": "Collapse sidebar",
  "展开侧栏": "Expand sidebar",
  "功能模式": "Features",
  "系统资源监视器": "System resource monitor",
  "操作通知": "Notifications",

  // Core feature titles and descriptions.
  "PBR 多通道合成": "PBR Channel Merge",
  "生成游戏可用的 _c 与 _n 通道贴图": "Generate game-ready _c and _n texture channels",
  "PBR 多通道拆分": "PBR Channel Split",
  "提取 BaseColor、Alpha、材质与法线通道": "Extract BaseColor, Alpha, material and normal channels",
  "为 DDS 贴图建立游戏原贴图映射并生成涂装配置": "Map DDS files to original game textures and generate a skin configuration",
  "Mipmap 生成": "Mipmap Generator",
  "将分层图片序列组装为单个 DDS": "Assemble an image sequence into one DDS",
  "批量转换图片并统一 DDS 压缩格式": "Convert images in batches using one DDS compression format",
  "将图片转换为黑白或彩色字符画，实时预览并导出 TXT / PNG": "Convert images to monochrome or color ASCII art with live preview and TXT / PNG export",
  "动漫 / 人像 / 商品等任意图片智能抠图，输出透明背景 PNG": "Cut out anime, portraits or products and export transparent PNG",
  "RealESRGAN 动漫特化模型，立绘插画放大 4 倍": "Upscale anime art and illustrations 4× with RealESRGAN",
  "RealESRGAN 通用模型，照片素材放大 4 倍": "Upscale photos and general images 4× with RealESRGAN",
  "从素材高度变化生成法线贴图，支持可移动光照预览": "Generate a normal map from source height with an interactive light preview",
  "从亮度或指定通道生成 8/16 位高度贴图": "Generate an 8/16-bit height map from luminance or a chosen channel",
  "生成 AO、曲率、世界法线等智能材质 Mesh Maps，并在模型上检查": "Generate AO, curvature, world normals and other Mesh Maps for smart materials, then inspect them on the model",
  "管理 War Thunder UserSkins 资源": "Manage War Thunder UserSkins assets",
  "方块": "Blocks",
  "波点": "Dots",
  "线条款描": "Hatching",
  "故障艺术": "Glitch Art",
  "像素排序": "Pixel Sorting",
  "坏块流动": "Datamosh",
  "信号撕裂": "Signal Tear",
  "数据腐蚀": "Data Decay",
  "CRT 显像管": "CRT Display",
  "信号重影": "Signal Echo",
  "迷彩生成": "Camouflage",
  "油画厚涂": "Oil Paint",
  "半调印刷": "Halftone Print",
  "素描炭笔": "Charcoal Sketch",
  "热感假彩": "Thermal Color",
  "十字绣": "Cross Stitch",
  "双色调": "Duotone",
  "水彩晕染": "Watercolor",
  "低多边形": "Low Poly",
  "像素画": "Pixel Art",
  "版画木刻": "Woodcut",
  "胶片颗粒": "Film Grain",
  "水波纹": "Water Ripple",
  "玻璃折射": "Glass Refraction",
  "马赛克拼贴": "Mosaic",
  "热浪扭曲": "Heat Distortion",
  "蜡笔粉彩": "Pastel",
  "幻彩全息": "Holographic",
  "将图片按亮度映射为实心方块马赛克，支持原图颜色与透明底，导出 PNG": "Map image brightness to solid mosaic blocks; preserve source colors or transparency and export PNG",
  "将图片按亮度映射为半调圆点，支持原图颜色与透明底，导出 PNG": "Map image brightness to halftone dots; preserve source colors or transparency and export PNG",
  "用不同角度的平行排线表现明暗，铜版画/素描风格，支持原图颜色与透明底": "Render shading with angled hatch lines for an engraving or sketch look",
  "通道色散、块位移与扫描线的故障屏风格，导出 PNG": "Create screen glitches with color separation, block shifts and scanlines",
  "按亮度阈值排序行内像素段，数据融化般的流动条纹": "Sort pixel runs by brightness to create flowing, melted-data streaks",
  "模拟视频编码坏块拖影，画面如编码损坏般融化流动": "Simulate video codec artifacts and flowing block trails",
  "水平撕裂带错位与通道色散，VHS 跳带的信号失控感": "Shift horizontal tear bands and color channels for a VHS tracking effect",
  "低色深量化、随机错扫与块级损坏的数字腐烂风格": "Combine low bit depth, scan errors and block damage for digital decay",
  "弧面畸变、荫罩栅格、辉光暗角与滚动亮带的老式显示器质感": "Add curved distortion, shadow mask, glow, vignette and scan bands",
  "多份错位半透明残影叠加，天线不良般的迷幻重影": "Layer offset translucent ghosts for an unstable analog signal",
  "从图片取色生成斑块/数码/豹纹等迷彩图案，导出 PNG": "Sample image colors to generate blotch, digital or leopard camouflage",
  "Kuwahara 最小方差均值滤波，笔触块状厚涂效果": "Use a Kuwahara filter for bold, painterly strokes",
  "圆/方/菱/线网点与 CMY 四色套印的印刷半调": "Print halftones with dot shapes and CMY overprinting",
  "反色减淡 + 轮廓加深 + 纸面颗粒的铅笔素描": "Create pencil sketches with color dodge, dark outlines and paper grain",
  "铁红/彩虹/夜视等渐变 LUT 假彩色映射": "Apply thermal, rainbow or night-vision false-color palettes",
  "色彩量化 + 交叉针脚与布纹的十字绣质感": "Create cross-stitch with color quantization, stitches and fabric texture",
  "暗部/亮部双色映射与软过渡，海报级双色调输出": "Map shadows and highlights to two colors with a soft transition",
  "fBm 驱动的多遍颜料浸润偏移与纸纹": "Blend pigment washes and paper texture using fBm",
  "三角网格均值取色与抖动，低多边形海报风": "Create low-poly posters from triangle color averages and dithering",
  "降采样 + 色阶量化 + 调色板量化的复古像素画": "Create retro pixel art with downsampling and palette quantization",
  "平行线雕版阴影与对比拉伸的木刻版画": "Create woodcut shading with engraved parallel lines",
  "复合噪点、光晕、褪色与暖调的胶片质感": "Add grain, bloom, fading and warmth for a film look",
  "正弦波纹偏移采样的水面折射": "Refract the image with sinusoidal water ripples",
  "模糊灰度梯度驱动的厚玻璃折射变形": "Simulate thick glass refraction from grayscale gradients",
  "瓦片量化、缝隙灌浆与抖动的马赛克拼贴": "Create mosaic tiles with grout and dithering",
  "正弦列偏移模拟热空气上升的视觉扭曲": "Distort columns to simulate rising hot air",
  "柔化、蜡笔颗粒、亮部晕开与纸纹的粉彩质感": "Combine softening, crayon grain, bloom and paper texture",
  "亮度驱动的全息幻彩渐变与扫描线": "Use brightness-driven holographic gradients and scanlines",

  // PBR, BLK, image processing and previews.
  "输入资源": "Input Assets",
  "PBR 贴图目录": "PBR Texture Folder",
  "选择贴图目录": "Choose Texture Folder",
  "或将文件夹拖到此处": "or drop a folder here",
  "当前输入": "Current Input",
  "暂无选择": "Nothing selected",
  "分辨率": "Resolution",
  "输出尺寸": "Output Size",
  "保持原始": "Keep Original",
  "Alpha 通道": "Alpha Channel",
  "纯黑": "Black",
  "纯白": "White",
  "DDS 格式": "DDS Format",
  "输入文件夹": "Input Folder",
  "导出文件夹": "Export Folder",
  "输出目录": "Output Folder",
  "打开输出目录": "Open Output Folder",
  "打开缓存目录": "Open Cache Folder",
  "输出设置": "Output Settings",
  "文件列表": "File List",
  "待拆分文件": "Files to Split",
  "待转换图片": "Images to Convert",
  "可批量选择或拖入": "Select multiple files or drop them here",
  "添加 DDS 文件": "Add DDS Files",
  "添加图片": "Add Images",
  "清空 DDS 列表": "Clear DDS List",
  "清空图片列表": "Clear Image List",
  "支持 _c.dds 与 _n.dds": "Supports _c.dds and _n.dds",
  "DDS 通道贴图": "DDS Channel Textures",
  "输出格式": "Output Format",
  "输出位深": "Output Bit Depth",
  "生成 Mipmap": "Generate Mipmap",
  "选择序列目录": "Choose Sequence Folder",
  "Mipmap 序列目录": "Mipmap Sequence Folder",
  "中间尺寸预滤波（实验）": "Intermediate-size Prefilter (experimental)",
  "仅用 p0 生成标准 DDS 对照与实验两份文件，适用于颜色纹理；法线、数据贴图请关闭。": "Generate standard and experimental DDS files from p0 for color textures. Disable this for normal or data maps.",
  "源图片": "Source Image",
  "抠图": "Cutout",
  "超分": "Upscale",
  "抠图前后对比": "Before / After Cutout",
  "添加图片开始 AI 抠图": "Add images to start AI cutout",
  "添加图片开始超分": "Add images to start upscaling",
  "动漫、人像、商品等任意图片 · 点击上方「添加图片」或直接拖进窗口": "Anime, portraits, products and more · Add images above or drop them here",
  "动漫超分适合立绘插画，通用超分适合照片和一般素材 · 点击上方「添加图片」或直接拖进窗口": "Anime upscale suits illustrations; general upscale suits photos · Add images above or drop them here",
  "拖动分割线对比原图与抠图结果 · PNG · JPG · WebP": "Drag the divider to compare source and cutout · PNG · JPG · WebP",
  "拖动分割线对比原图与超分结果 · RealESRGAN 本地推理 · 输出为原图 2–4 倍分辨率": "Drag the divider to compare source and upscale · Local RealESRGAN · 2–4× resolution",
  "该图片还没有抠图结果，运行后可对比前后效果": "No cutout result yet. Run the task to compare before and after.",
  "该图片还没有超分结果，运行后可对比前后效果": "No upscale result yet. Run the task to compare before and after.",
  "抠图模型": "Cutout Model",
  "动漫专精（AnimeSeg，推荐）": "Anime Specialist (AnimeSeg, recommended)",
  "动漫特化（ToonOut）": "Anime Stylized (ToonOut)",
  "动漫标准（ISNet）": "Anime Standard (ISNet)",
  "动漫精细（RTMDet + 精修）": "Anime Detail (RTMDet + refinement)",
  "高质量抠图（BiRefNet 1024）": "High-quality Cutout (BiRefNet 1024)",
  "轻量快速（BiRefNet Lite）": "Fast & Light (BiRefNet Lite)",
  "动漫超分模型": "Anime Upscale Model",
  "通用超分模型": "General Upscale Model",
  "模型保存在应用数据文件夹，下载完成后即可离线使用，无需 ComfyUI": "Models are stored in app data and work offline after download. ComfyUI is not required.",
  "RealESRGAN 动漫特化模型（约 18 MB），适合立绘、插画等二次元图片；下载后可离线使用": "RealESRGAN anime model (~18 MB) for character art and illustrations; works offline after download",
  "RealESRGAN 通用模型（约 64 MB），适合照片和一般素材；下载后可离线使用": "RealESRGAN general model (~64 MB) for photos and other images; works offline after download",
  "下载模型": "Download Model",
  "下载 GPU 运行库": "Download GPU Runtime",
  "下载 ViTMatte（约 99 MB）": "Download ViTMatte (~99 MB)",
  "下载降噪组件": "Download Denoiser",
  "卸载": "Uninstall",
  "GPU 加速": "GPU Acceleration",
  "超分倍率": "Upscale Factor",
  "放大 2 倍": "Upscale 2×",
  "精细发丝边缘（实验性）": "Fine Hair Edges (experimental)",
  "启用原分辨率边缘精修": "Refine edges at source resolution",
  "高分辨率细节补全（实验性）": "High-resolution Detail Recovery (experimental)",
  "尝试补回高分辨率边缘细节": "Try to recover fine edge details",
  "仅适用于动漫专精（AnimeSeg），默认关闭。局部重算边缘，耗时增加；部分图片可能变软或出现色边，无法保证找回完全漏掉的头发。": "AnimeSeg only; off by default. Recomputes edges locally at extra cost. Some images may soften or show fringes; missing hair cannot always be recovered.",
  "仅适用于动漫专精（AnimeSeg），默认关闭。会把主体按区域分成多组局部推理；只有两组裁切都明确识别为前景时才补回边缘。耗时相应增加，复杂背景线条仍可能被误判。": "AnimeSeg only; off by default. Runs local inference on subject regions and restores an edge only when both crops detect foreground. Takes longer and may still misread complex backgrounds.",

  // BLK mapping.
  "涂装配置": "Skin Configuration",
  "DDS 映射工作区": "DDS Mapping Workspace",
  "选择目录后扫描 DDS": "Choose a folder to scan DDS files",
  "选择已合成 DDS 所在目录，查看贴图缩略图与游戏原贴图名之间的映射。": "Choose the folder with merged DDS files to map texture thumbnails to original game texture names.",
  "每行直接编辑游戏原贴图名与指令：↑↓/Enter 在行间移动，原名支持批量填充。N 文件固定 replace_tex；set_tex 固定迷彩时可能需要 camo 参数。": "Edit each original texture name and command in the list. Use ↑↓/Enter to move between rows or fill names in bulk. N files always use replace_tex; fixed camouflage may need the camo parameter on set_tex.",
  "BLK 文本预览": "BLK Text Preview",
  "BLK 文件名": "BLK Filename",
  "BLK 文件名无效。": "Invalid BLK filename.",
  "DDS 文件夹": "DDS Folder",
  "贴图目录": "Texture Folder",
  "重新扫描": "Rescan",
  "生成 BLK": "Generate BLK",
  "浏览器预览会下载 BLK；桌面版直接写入 DDS 目录。": "The browser downloads the BLK; the desktop app writes it into the DDS folder.",
  "交付准备": "Delivery Preparation",
  "检查 BLK 与引用贴图，生成可分享的 ZIP": "Check the BLK and referenced textures, then create a shareable ZIP",
  "选择包含 BLK 和 DDS/TGA 的涂装目录，检查后生成 ZIP。": "Choose a skin folder containing a BLK and DDS/TGA files, then create a ZIP.",
  "等待选择目录": "Choose a folder",
  "等待检查": "Waiting to check",
  "检查未通过": "Checks failed",
  "检查通过": "Checks passed",
  "请选择一份 BLK": "Choose a BLK",
  "将收入 ZIP": "Included in ZIP",
  "未收录文件": "Excluded files",
  "BLK 未引用": "Not referenced by BLK",
  "去 BLK 生成": "Go to BLK Generator",
  "打包此目录": "Package This Folder",
  "打包设置": "Package Settings",
  "涂装目录": "Skin Folder",
  "使用的 BLK": "Selected BLK",
  "包名": "Package Name",
  "默认与 BLK 同名": "Defaults to the BLK name",
  "ZIP 内仅包含 BLK 及其引用的 DDS/TGA，解压到 UserSkins 即可。": "The ZIP contains only the BLK and its referenced DDS/TGA files. Extract it into UserSkins.",
  "生成 ZIP": "Create ZIP",
  "BLK 配置": "BLK configuration",
  "需修复": "Fix",
  "建议": "Advice",
  "包名无效。": "Invalid package name.",
  "正在检查文件，请稍候。": "Checking files…",
  "请重新扫描涂装目录。": "Rescan the skin folder.",
  "请选择涂装目录。": "Choose a skin folder.",
  "目录中没有 BLK，请先生成。": "No BLK found. Generate one first.",
  "目录中有多份 BLK，请选择本次打包的一份。": "Multiple BLKs found. Select one to package.",
  "所选 BLK 已不存在，请重新选择。": "The selected BLK is missing. Choose it again.",
  "BLK 文件名不安全。": "Unsafe BLK filename.",
  "BLK 没有可打包的贴图映射。": "The BLK has no texture mappings to package.",
  "BLK 不是 UTF-8/ASCII 文本。": "The BLK is not UTF-8/ASCII text.",
  "重复的 from 字段。": "Duplicate from field.",
  "重复的 to 字段。": "Duplicate to field.",
  "无法解析的映射字段。": "Could not parse a mapping field.",
  "无法解析的 BLK 内容。": "Could not parse the BLK content.",
  "涂装文件发生变化，请重新扫描。": "Skin files changed. Rescan the folder.",
  "源文件在打包期间发生变化，请重新扫描。": "Source files changed during packaging. Rescan the folder.",
  "贴图或 BLK 在预览后发生变化，请重新扫描。": "A texture or BLK changed after preview. Rescan the folder.",
  "涂装检查未通过，请重新扫描。": "Skin checks failed. Rescan the folder.",
  "目标 ZIP 在确认后发生变化，请重新选择保存位置。": "The destination ZIP changed after confirmation. Choose where to save it again.",
  "目标 ZIP 在打包期间发生变化，旧文件未被覆盖。": "The destination ZIP changed during packaging. The old file was kept.",
  "ZIP 目标不是文件。": "The ZIP destination is not a file.",
  "请选择 ZIP 输出文件。": "Choose a ZIP output file.",
  "请选择已有的涂装目录。": "Choose an existing skin folder.",
  "DDS 没有完整 Mipmap 链，远景可能闪烁。": "This DDS has no full mipmap chain and may shimmer at a distance.",
  "ZIP 已生成": "ZIP Created",
  "确认覆盖 ZIP": "Overwrite ZIP?",

  // ASCII, style lab and material maps.
  "让图片变成字符画": "Turn an Image into ASCII Art",
  "选择或拖入一张图片，实时调整字符与色彩。": "Choose or drop an image, then adjust characters and colors live.",
  "把图片变成新的风格": "Give Your Image a New Style",
  "选择或拖入一张图片，右侧调参数，实时出效果。": "Choose or drop an image, then adjust the controls for a live preview.",
  "效果预览": "Effect Preview",
  "字符效果": "Character Effect",
  "字符密度": "Character Density",
  "字符集": "Character Set",
  "由疏到密的字符": "Characters from sparse to dense",
  "2–95 个可打印 ASCII 字符；空格也计入。": "2–95 printable ASCII characters, including spaces.",
  "标准": "Standard",
  "详细": "Detailed",
  "自定义": "Custom",
  "黑白字符": "Monochrome Characters",
  "保留原图颜色": "Keep Source Colors",
  "保留原图": "Keep Original",
  "颜色模式": "Color Mode",
  "背景": "Background",
  "黑底": "Black Background",
  "白底": "White Background",
  "透明底（PNG）": "Transparent Background (PNG)",
  "亮度": "Brightness",
  "对比度": "Contrast",
  "反相": "Invert",
  "抖动": "Dithering",
  "有序（Bayer）": "Ordered (Bayer)",
  "误差扩散": "Error Diffusion",
  "图形大小": "Shape Size",
  "长宽比": "Aspect Ratio",
  "排线层数": "Hatch Layers",
  "排线角度": "Hatch Angle",
  "文件格式": "File Format",
  "PNG · 字符图片": "PNG · Character Image",
  "TXT · 纯文本": "TXT · Plain Text",
  "导出倍率（PNG）": "Export Scale (PNG)",
  "TXT 保留字符、空格与换行。": "TXT preserves characters, spaces and line breaks.",
  "导出使用完整字符网格，不受预览缩放影响。": "Export uses the full character grid and ignores preview zoom.",
  "复制字符": "Copy Characters",
  "导出 PNG": "Export PNG",
  "缩放": "Zoom",
  "清晰字符": "Crisp Characters",
  "细腻渐变": "Smooth Gradient",
  "报纸半调": "Newspaper Halftone",
  "像素方块": "Pixel Blocks",
  "铜版画": "Engraving",
  "添加素材": "Add Source",
  "添加素材后查看贴图与光照预览": "Add a source image to preview maps and lighting",
  "生成贴图": "Generated Maps",
  "光照效果": "Lighting Preview",
  "贴图预览": "Map Preview",
  "复位视图与光源": "Reset View and Light",
  "法线强度": "Normal Strength",
  "法线方向": "Normal Direction",
  "法线设置": "Normal Settings",
  "高度来源": "Height Source",
  "高度位深": "Height Bit Depth",
  "高度调整": "Height Adjustment",
  "同时输出高度图": "Also Export Height Map",
  "平滑半径": "Smoothing Radius",
  "边界模式": "Edge Mode",
  "平铺纹理 · 循环采样": "Tiled Texture · Repeat Sampling",
  "普通素材 · 边缘钳制": "Regular Image · Clamp Edges",
  "反相（默认白色凸起）": "Invert (white is raised by default)",
  "R 通道": "R Channel",
  "G 通道": "G Channel",
  "B 通道": "B Channel",
  "亮度／灰度数据": "Luminance / Grayscale Data",
  "8 位": "8-bit",
  "16 位灰度 PNG": "16-bit Grayscale PNG",
  "8 位灰度 PNG": "8-bit Grayscale PNG",
  "透明区域输出中性高度及平坦法线。数据贴图不附加源图 ICC。缩略预览供参考，导出使用原始尺寸。": "Transparent areas produce neutral height and flat normals. Data maps omit source ICC. The thumbnail is for reference; export uses source resolution.",
  "明暗会被解释成表面凹凸，不等同于真实几何高度。光照预览使用固定材质，仅供检查强度和方向。": "Brightness is interpreted as surface relief, not real geometry. Lighting preview uses a fixed material to inspect strength and direction.",

  // Mesh-map baking.
  "01 / 智能材质 Mesh Maps": "01 / Smart Material Mesh Maps",
  "02 / 烘焙质量": "02 / Bake Quality",
  "03 / 导出": "03 / Export",
  "01　导入模型": "01  Import Model",
  "02　检查 UV": "02  Inspect UV",
  "03　烘焙贴图": "03  Bake Maps",
  "从一个模型开始": "Start with a Model",
  "生成智能材质识别所需的 Mesh Maps，并直接在模型上检查结果。": "Generate the Mesh Maps used by smart materials and inspect the result directly on your model.",
  "浏览器可查看界面；导入与烘焙请在桌面软件中使用。": "You can inspect the UI in the browser. Import and bake in the desktop app.",
  "请在桌面软件中导入模型并烘焙。": "Import and bake a model in the desktop app.",
  "导入模型": "Import Model",
  "选择模型": "Choose Model",
  "OBJ · GLB · glTF 静态三角网格": "OBJ · GLB · glTF static triangle meshes",
  "对象 / 材质": "Objects / Materials",
  "烘焙设置": "Bake Settings",
  "烘焙参数": "Bake Parameters",
  "准备烘焙任务": "Preparing bake task",
  "实时烘焙阶段": "Live Bake Stage",
  "正在准备材质": "Preparing materials",
  "正在检测 GPU…": "Detecting GPU…",
  "0 个材质 · 预计 0 张贴图": "0 materials · 0 expected maps",
  "贴图尺寸": "Map Size",
  "16 位（AO/厚度/曲率/位置/世界法线）": "16-bit (AO / thickness / curvature / position / world normal)",
  "AO / 厚度采样": "AO / Thickness Samples",
  "128 次光线采样 · 8 位灰度": "128 ray samples · 8-bit grayscale",
  "光线追踪与边缘": "Ray Tracing & Edges",
  "边缘扩展（px）": "Edge Padding (px)",
  "射线距离": "Ray Distance",
  "遮挡范围": "Occlusion Range",
  "默认包围盒对角线的 10%": "10% of the bounding-box diagonal by default",
  "仅同一对象": "Same Object Only",
  "全部对象互相影响": "All Objects Affect Each Other",
  "UV 工作流": "UV Workflow",
  "导入时 UV 处理": "UV Handling on Import",
  "智能保留": "Smart Preserve",
  "全部重新展开": "Unwrap All",
  "严格使用源 UV": "Use Source UV Strictly",
  "智能保留会优先使用合格源 UV，仅修复缺失或越界的材质；UV 重叠（镜像/分层堆叠）与零面积退化面视为无害设计，保留原样。烘焙贴图供智能材质制作使用。": "Smart Preserve keeps valid source UVs and fixes only missing or out-of-range materials. Mirrored or stacked UVs and degenerate triangles are treated as intentional. The maps are made for smart-material workflows.",
  "当前材质 UV 通道": "Current Material UV Channel",
  "检查当前材质 UV": "Inspect Current Material UV",
  "选择材质检查 UV": "Select a material to inspect its UVs",
  "勾选决定输出，点击名称检查 UV": "Check materials to include; click a name to inspect UVs",
  "全选": "Select All",
  "UV 线框": "UV Wireframe",
  "UV 线框（检查用）": "UV Wireframe (inspection)",
  "切线法线": "Tangent Normal",
  "切线空间法线（同模平面）": "Tangent-space Normal (same-mesh planar)",
  "世界空间法线": "World-space Normal",
  "环境遮蔽": "Ambient Occlusion",
  "环境遮蔽 AO": "Ambient Occlusion (AO)",
  "厚度": "Thickness",
  "厚度 Thickness": "Thickness",
  "曲率": "Curvature",
  "曲率 Curvature": "Curvature",
  "位置": "Position",
  "位置 Position": "Position",
  "材质 ID": "Material ID",
  "几何图": "Geometry Maps",
  "计算设备": "Compute Device",
  "桌面版可检测 DXR 显卡": "The desktop app can detect DXR GPUs",
  "AO 与厚度使用 GPU；其余 Mesh Map 由模型几何直接生成。": "AO and thickness use the GPU; the other Mesh Maps are generated from model geometry.",
  "AI 降噪（仅用于 AO）": "AI Denoising (AO only)",
  "降噪": "Denoising",
  "快速": "Fast",
  "精细": "Fine",
  "结果先缓存在应用数据目录，导出时选择目标文件夹": "Results are cached in app data; choose a destination when exporting",
  "导出全部贴图": "Export All Maps",
  "导出设置": "Export Settings",
  "输出材质": "Output Materials",
  "当前工作流": "Current Workflow",
  "透视": "Perspective",
  "线框": "Wireframe",
  "着色 + AO": "Shaded + AO",
  "Alt+左键 旋转 · 中键 平移 · 滚轮 缩放 · F 聚焦 · 1/3/7 前侧顶视图": "Alt+Left drag Rotate · Middle drag Pan · Wheel Zoom · F Focus · 1/3/7 Front/Side/Top",

  // Remaining controls and status text.
  "涂装启用状态通过文件夹名称管理": "Skin enabled state is managed through folder names",
  "导入涂装": "Import Skin",
  "整理": "Organize",
  "名称 A-Z": "Name A–Z",
  "名称 Z-A": "Name Z–A",
  "大小降序": "Size: Largest First",
  "最近修改": "Recently Modified",
  "未设置涂装目录": "Skin folder not set",
  "目录已连接": "Folder connected",
  "浏览器预览无法读取本地图片，请在 Tauri 窗口中使用": "Browser preview cannot read local images; use the desktop app",
  "自动检测": "Auto Detect",
  "高级设置": "Advanced Settings",
  "内存": "Memory",
  "显存": "VRAM",
  "导出 _c Alpha": "Export _c Alpha",
  "导出格式": "Export Format",
  "尚未添加图片": "No images added",
  "已安装 · 17.5 MB": "Installed · 17.5 MB",
  "未安装 · 共 63.9 MB": "Not installed · 63.9 MB total",
  "材质贴图": "Material Maps",
  "检测设备中…": "Detecting devices…",
  "正在读取模型状态…": "Reading model status…",
  "立绘 / 素材 4 倍超分": "4× Art / Asset Upscale",
  "等待 Worker": "Waiting for worker",
  "等待任务": "Waiting for task",

  // Accessibility labels, tooltips and input hints.
  "2–4 倍；模型原生 4 倍，其余倍率在 4 倍结果上重采样": "2–4×; the model runs at 4× and other scales resample that result",
  "AI 抠图输出文件夹": "AI Cutout Output Folder",
  "ASCII 图片预览及拖放区域": "ASCII image preview and drop area",
  "ASCII 预览": "ASCII Preview",
  "ASCII 预览缩放": "ASCII Preview Zoom",
  "BLK 映射规则": "BLK Mapping Rules",
  "Mipmap Alpha 通道": "Mipmap Alpha Channel",
  "Mipmap DDS 格式": "Mipmap DDS Format",
  "Mipmap 输入文件夹": "Mipmap Input Folder",
  "Mipmap 输出文件夹": "Mipmap Output Folder",
  "PBR Alpha 通道": "PBR Alpha Channel",
  "PBR DDS 格式": "PBR DDS Format",
  "PBR 拆分输出文件夹": "PBR Split Output Folder",
  "PBR 输入文件夹": "PBR Input Folder",
  "PBR 输出文件夹": "PBR Output Folder",
  "UV 检查，红色标记问题面": "UV inspection; problem faces are marked red",
  "任务进度": "Task Progress",
  "切换透视 / 正交": "Switch Perspective / Orthographic",
  "图片转 DDS Alpha 通道": "Image to DDS Alpha Channel",
  "图片转 DDS 格式": "Image to DDS Format",
  "图片转 DDS 输出文件夹": "Image to DDS Output Folder",
  "复位视图": "Reset View",
  "复制当前日志": "Copy Current Log",
  "将超过目标尺寸的贴图等比缩小（如 8K → 6K / 4K），小图不放大": "Scale textures larger than the target (e.g. 8K → 6K / 4K) without upscaling smaller images",
  "当前设备不支持 AO": "The current device does not support AO",
  "当前设备不支持厚度图": "The current device does not support thickness maps",
  "拆分导出格式": "Split Export Format",
  "拖动调整光源": "Drag to adjust the light",
  "排序方式": "Sort Order",
  "推荐动漫专精 AnimeSeg：针对二次元角色复杂背景回归验证，优先去除远景人物和摆设；仍可自行选择通用 BiRefNet 或 ToonOut": "AnimeSeg is recommended for complex anime backgrounds. You can still choose BiRefNet or ToonOut.",
  "搜索涂装": "Search Skins",
  "搜索涂装…": "Search skins…",
  "收起材质面板": "Collapse Materials Panel",
  "收起烘焙参数面板": "Collapse Bake Settings Panel",
  "收起运行记录": "Collapse Activity",
  "显示选项": "Display Options",
  "更新可用": "Update Available",
  "材质输出文件夹": "Material Output Folder",
  "模型烘焙三维工作区": "Model Baking 3D Workspace",
  "模型贴图预览": "Model Map Preview",
  "烘焙视图": "Bake Views",
  "烘焙进度": "Bake Progress",
  "烘焙阶段": "Bake Stage",
  "素材列表": "Source List",
  "素材贴图预览": "Source Map Preview",
  "聚焦所选对象": "Focus Selected Object",
  "聚焦所选对象 · F": "Focus Selected Object · F",
  "视图显示工具": "Viewport Display Tools",
  "请选择输出目录": "Choose an output folder",
  "质量预设": "Quality Preset",
  "超分输出文件夹": "Upscale Output Folder",
  "预览类型": "Preview Type",
  "预览缩放": "Preview Zoom",
  "预设名称": "Preset Name",
  "风格化预览": "Stylized Preview",
  "默认与目录同名": "Defaults to the folder name",
  "已就绪": "Ready",
  "配置完成，可开始运行": "Ready to run",
  "请配置全局输出目录": "Set a global output folder",
  "请选择输入文件夹。": "Choose an input folder.",
  "请选择 DDS 文件夹。": "Choose a DDS folder.",
  "请添加 DDS 文件。": "Add DDS files.",
  "请添加图片文件。": "Add image files.",
  "请添加图片。": "Add images.",
  "请在设置中选择默认输出目录。": "Choose a default output folder in Settings.",
  "请先选择输入文件或目录。": "Choose an input file or folder first.",
  "请选择输出文件夹。": "Choose an output folder.",
  "请选择输出目录。": "Choose an output folder.",
  "请在桌面软件中生成贴图。": "Generate maps in the desktop app.",
  "请导入图片并生成有效预览。": "Import an image and generate a valid preview.",
  "请导入模型。": "Import a model.",
  "请选择输出材质。": "Choose output materials.",
  "请选择输出类型。": "Choose at least one output map.",
  "任务正在运行。": "A task is running.",
  "另一个任务正在运行，请等待完成后重试。": "Another task is running. Wait for it to finish and try again.",
  "抠图正在运行，请稍候。": "Cutout is running. Please wait.",
  "超分正在运行，请稍候。": "Upscale is running. Please wait.",
  "模型正在下载中，请稍候。": "The model is downloading. Please wait.",
  "当前模型未安装，请先在「抠图模型」中下载。": "The selected model is not installed. Download it from Cutout Model.",
  "请先在右侧栏下载精细发丝边缘模型，或关闭实验选项。": "Download the fine-hair model in the right panel or turn off the experimental option.",
  "正在导出…": "Exporting…",
  "正在读取图片…": "Reading image…",
  "正在生成字符画…": "Generating ASCII art…",
  "正在生成效果…": "Generating effect…",
  "正在检查 UV…": "Inspecting UVs…",
  "UV 检查失败，请重新检查后烘焙。": "UV inspection failed. Inspect the UVs again before baking.",
  "遮蔽距离必须大于 0。": "Occlusion distance must be greater than 0.",
  "边缘扩展应为 0–128 的整数。": "Edge padding must be an integer from 0 to 128.",
  "当前设备不支持 DXR 1.1 光线追踪。": "The selected device does not support DXR 1.1 ray tracing.",
  "AI 降噪组件未下载，请先点击「下载降噪组件」。": "The AI denoiser is missing. Download it first.",
  "正在检查内置 OIDN 组件…": "Checking bundled OIDN component…",
  "暂无已安装模型或运行库。": "No models or runtimes installed.",
  "替换图片": "Replace Image",
  "无法运行": "Cannot Run",
  "保存失败": "Save Failed",
  "保存设置失败": "Failed to Save Settings",
  "已更新": "Updated",
  "选择失败": "Selection Failed",
  "打开失败": "Open Failed",
  "配置已保存": "Settings Saved",
  "设置已写入本地配置。": "Settings saved to local configuration.",
  "设置已保存到浏览器预览存储。": "Settings saved to browser preview storage.",
  "自动检查更新已开启": "Automatic update checks enabled",
  "自动检查更新已关闭": "Automatic update checks disabled",
  "重置设置": "Reset Settings",
  "所有路径和选项将恢复默认值，确定继续？": "Restore all paths and options to their defaults?",
  "重置失败": "Reset Failed",
  "取消": "Cancel",
  "确认": "Confirm",
  "确定": "OK"
};

function translateCore(value) {
  if (Object.hasOwn(EN, value)) return EN[value];
  let pack = value.match(/^(需修复|建议) · (?:(.+?) · )?(.+)$/);
  if (pack) return `${translateCore(pack[1])} · ${pack[2] ? `${pack[2]} · ` : ''}${translateCore(pack[3])}`;
  pack = value.match(/^(\d+) 个文件 · ([\d,]+) 字节$/);
  if (pack) return `${pack[1]} files · ${pack[2]} bytes`;
  pack = value.match(/^另有 (\d+) 个文件未被 BLK 引用，不会收入 ZIP。$/);
  if (pack) return `${pack[1]} unreferenced files will be excluded from the ZIP.`;
  pack = value.match(/^贴图尺寸 (\d+)×(\d+) 不属于常见投稿尺寸。$/);
  if (pack) return `Texture size ${pack[1]}×${pack[2]} is unusual for submission.`;
  pack = value.match(/^目录中存在大小写冲突的文件名：(.+)。$/);
  if (pack) return `Filename case collision in this folder: ${pack[1]}.`;
  pack = value.match(/^(.+) 在检查后发生变化，请重新扫描。$/);
  if (pack) return `${pack[1]} changed after the checks. Rescan the folder.`;
  pack = value.match(/^(.+) 在打包时发生变化，请重新扫描。$/);
  if (pack) return `${pack[1]} changed during packaging. Rescan the folder.`;
  pack = value.match(/^贴图 (.+) 的文件名大小写与 BLK 不一致。$/);
  if (pack) return `Texture ${pack[1]} differs in letter case from the BLK.`;
  pack = value.match(/^找不到贴图 (.+)。$/);
  if (pack) return `Texture ${pack[1]} was not found.`;
  pack = value.match(/^贴图路径 (.+) 不安全或不在当前目录。$/);
  if (pack) return `Texture path ${pack[1]} is unsafe or outside this folder.`;
  pack = value.match(/^贴图 (.+) 不是支持的 DDS\/TGA 格式。$/);
  if (pack) return `Texture ${pack[1]} is not a supported DDS/TGA file.`;
  pack = value.match(/^(DDS|TGA) 无法解码：(.+)$/);
  if (pack) return `${pack[1]} could not be decoded: ${pack[2]}`;
  pack = value.match(/^DDS 图像数据不完整：(.+)$/);
  if (pack) return `DDS image data is incomplete: ${pack[1]}`;
  pack = value.match(/^原贴图名 (.+) 重复。$/);
  if (pack) return `Original texture name ${pack[1]} is duplicated.`;
  pack = value.match(/^(replace_tex|set_tex) 缺少 from 或 to。$/);
  if (pack) return `${pack[1]} is missing from or to.`;
  pack = value.match(/^(replace_tex|set_tex) 规则块没有结束。$/);
  if (pack) return `${pack[1]} block is not closed.`;
  pack = value.match(/^无法解析的 BLK 规则块 (.+)。$/);
  if (pack) return `Unsupported BLK rule block ${pack[1]}.`;
  if (value === '无法解析的映射字段。') return 'Could not parse a mapping field.';
  if (value === '无法解析的 BLK 内容。') return 'Could not parse the BLK content.';
  if (value === '重复的 from 字段。') return 'Duplicate from field.';
  if (value === '重复的 to 字段。') return 'Duplicate to field.';
  let match = value.match(/^当前版本 (.+)$/);
  if (match) return `Version ${match[1]}`;
  match = value.match(/^(\d+) 个材质 · 预计 (\d+) 张贴图$/);
  if (match) return `${match[1]} materials · ${match[2]} expected maps`;
  match = value.match(/^(\d+) 个涂装$/);
  if (match) return `${match[1]} skins`;
  match = value.match(/^(\d+) 张素材$/);
  if (match) return `${match[1]} source images`;
  match = value.match(/^(\d+) 项$/);
  if (match) return `${match[1]} items`;
  match = value.match(/^(\d+) 次$/);
  if (match) return `${match[1]} samples`;
  match = value.match(/^内存：已用 (.+) \/ 共 (.+)\n(.+) · 显存已用 (.+) \/ 共 (.+)$/);
  if (match) return `Memory: ${match[1]} / ${match[2]}\n${match[3]} · VRAM: ${match[4]} / ${match[5]}`;
  match = value.match(/^输出到 (.+)$/);
  if (match) return `Output to ${match[1]}`;
  match = value.match(/^(.+)\.blk · (\d+) 条规则$/);
  if (match) return `${match[1]}.blk · ${match[2]} rules`;
  return value;
}

export function translateText(source, language = "zh-CN") {
  if (language !== "en" || typeof source !== "string" || !source.trim()) return source;
  const leading = source.match(/^\s*/)?.[0] || "";
  const trailing = source.match(/\s*$/)?.[0] || "";
  return leading + translateCore(source.trim()) + trailing;
}

export function createLocalization(root) {
  let language = "zh-CN";
  const textState = new WeakMap();
  const attrState = new WeakMap();
  const attributes = ["aria-label", "title", "placeholder"];

  function updateText(node) {
    if (!node.nodeValue?.trim() || node.parentElement?.closest("script, style")) return;
    const current = node.nodeValue;
    let record = textState.get(node);
    if (!record || current !== record.output) record = { source: current, output: current };
    const output = translateText(record.source, language);
    record.output = output;
    textState.set(node, record);
    if (current !== output) node.nodeValue = output;
  }

  function updateAttribute(element, name) {
    const current = element.getAttribute(name);
    if (current === null) return;
    let records = attrState.get(element);
    if (!records) { records = new Map(); attrState.set(element, records); }
    let record = records.get(name);
    if (!record || current !== record.output) record = { source: current, output: current };
    const output = translateText(record.source, language);
    record.output = output;
    records.set(name, record);
    if (current !== output) element.setAttribute(name, output);
  }

  function updateTree(node) {
    if (node.nodeType === 3) { updateText(node); return; }
    if (node.nodeType !== 1) return;
    const elements = [node, ...node.querySelectorAll("*")];
    for (const element of elements) {
      for (const name of attributes) updateAttribute(element, name);
      for (const child of element.childNodes) if (child.nodeType === 3) updateText(child);
    }
  }

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData") updateText(mutation.target);
      else if (mutation.type === "attributes") updateAttribute(mutation.target, mutation.attributeName);
      else for (const node of mutation.addedNodes) updateTree(node);
    }
  });
  observer.observe(root, {
    childList: true, characterData: true, attributes: true, subtree: true,
    attributeFilter: attributes
  });

  return {
    setLanguage(next) { language = next === "en" ? "en" : "zh-CN"; updateTree(root); },
    disconnect() { observer.disconnect(); }
  };
}
